title: US Money
description:

url: http://localhost:3000
github-username: vhammon
repository: usmoney-v1
branch: master

author:
  email:
  name: Virginia Hammon
  photo:
  url: https://usmoney.us/
  bio: Hello I am Virginia! Of friendship on inhabiting diminution discovered as. Did friendly eat breeding building few nor. Object he barton no effect played valley afford.

company:
  name: US Money
  url: usmoney.us
  location: Lake Oswego, OR
  logo:
  phone:

touch-icon:
fav-icon:

cloudinary-name:

analytics:
  google:
  momently:
  hotjar:

reCaptcha:
  siteKey:
  secret:

mailchimp:
  post:
  hidden:

lead-post-script:

form-submit-script:

privacy-policy-comment: 'Privacy: Policy: Your email address will not be published or shared.'

privacy-policy-lead: 'Privacy Policy: We hate spam and promise to keep your email address safe.'

comment-policy: 'Comment Policy: We do our best to respond particularly on new articles, but don’t have the ability to respond to every comment. Insults and disrespectful comments are not accepted. Please do not include links not pertinent to the discussion. Thank you.'

default-right-aside-cta:



# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: .tmp/src
destination: .tmp/dist
include: [_redirects, _headers]
exclude: ['assets']

algolia:
  application_id:
  index_name:
  search_only_api_key:


# Enables future posts (posts with dates in the future) and drafts
future: false
show_drafts: false
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
# limit_posts: 10

# Permalink structure and pagination options
permalink: :categories/:year/:month/:title/

# Markdown library and options
markdown: kramdown
highlighter: rouge

# Extending Jekyll
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jemoji
  - jekyll-typogrify
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

collections_dir: my_collections

collections:
  social:
    output: false
  comments:
    output: false
  leads:
    output: true
    permalink: /:categories/free-:title/
  chapter-1:
    output: true
    permalink: /book/chapter-1/:title/
  chapter-2:
    output: true
    permalink: /book/chapter-2/:title/
  chapter-3:
    output: true
    permalink: /book/chapter-3/:title/
  chapter-4:
    output: true
    permalink: /book/chapter-4/:title/
  chapter-5:
    output: true
    permalink: /book/chapter-5/:title/
  chapter-6:
    output: true
    permalink: /book/chapter-6/:title/
  chapter-7:
    output: true
    permalink: /book/chapter-7/:title/
  chapter-8:
    output: true
    permalink: /book/chapter-8/:title/
  chapter-9:
    output: true
    permalink: /book/chapter-9/:title/
  chapter-10:
    output: true
    permalink: /book/chapter-10/:title/
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: post
      is-post: true
      cta: "&ldquo;Thank you for being a patron of my site and I hope you enjoy the read.&rdquo;"
      comments: true
      comment-locked: false
      dropcap: true
      download: true
  -
    scope:
      path: ""      # empty string for all files
      type: pages   # limit to posts
    values:
      layout: default
      comments: false
      pin-it: true
  -
    scope:
      path: ""      # empty string for all files
      type: chapter-1, chapter-2   # limit to posts
    values:
      layout: post
      comments: false
      pin-it: true
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

############################################################
# Site configuration for the Auto-Pages feature
autopages:
  enabled: true

  collections:
    layouts:
      - 'autopage.html'
    title: 'US Money :coll' # :coll is replaced by the collection name
    permalink: '/book/:coll'

  categories:
    layouts:
      - 'autopage.html'
    title: ':cat Posts'
    permalink: '/category/:cat'

  tags:
    layouts:
      - 'autopage.html'
    title: 'Posts in category :tag'
    permalink: '/category/:tag'
