title: US Money
description:

url: http://localhost:3000
github-username: vhammon
repository: usmoney-v1
branch: master

author:
  email:
  name: Virginia Hammon
  photo: virginia.png
  url: https://usmoney.us/
  bio: Hello I am Virginia! Of friendship on inhabiting diminution discovered as. Did friendly eat breeding building few nor. Object he barton no effect played valley afford.

company:
  name: US Money
  url: usmoney.us
  location: Lake Oswego, OR
  logo: https://res.cloudinary.com/usmoney/image/upload/v1535135004/us-money-logo.png
  logo-alt-text: US Money book title logo
  phone:

touch-icon:
fav-icon:

cloudinary-name: usmoney

algolia:
  application_id: XTP19ZA183
  index_name: us-money-index
  search_only_api_key: 7a38139c7e666cf1c8c1a47bfbce324f

analytics:
  google:
  momently:
  hotjar:

reCaptcha:
  siteKey:
  secret:

mailchimp:
  post:
  hidden:

lead-post-script:

form-submit-script:

privacy-policy-comment: 'Privacy: Policy: Your email address will not be published or shared.'

privacy-policy-lead: 'Privacy Policy: We hate spam and promise to keep your email address safe.'

comment-policy: 'Comment Policy: We do our best to respond particularly on new articles, but don’t have the ability to respond to every comment. Insults and disrespectful comments are not accepted. Please do not include links not pertinent to the discussion. Thank you.'

default-right-aside-cta:



# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: .tmp/src
destination: .tmp/dist
include: [_redirects, _headers]
exclude: ['assets']

# Enables future posts (posts with dates in the future) and drafts
future: false
show_drafts: false
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
# limit_posts: 10

# Permalink structure and pagination options
permalink: :categories/:title/

# Markdown library and options
markdown: kramdown
highlighter: rouge

# Extending Jekyll
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jemoji
  - jekyll-typogrify
  - jekyll-algolia
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

collections_dir: my_collections

collections:
  book-reviews:
    output: false
  comments:
    output: false

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      layout: post
      is-post: true
      cta: "&ldquo;Thank you for being a patron of my site and I hope you enjoy the read.&rdquo;"
      comments: true
      comment-locked: false
      left-aside: true
      right-aside-top: true
      right-aside-bottom: true
      bottom-cta: true
      pin-it: true
      dropcap: true
      download: true
      download-file:
  -
    scope:
      path: ""      # empty string for all files
      type: pages   # limit to posts
    values:
      layout: default
      comments: false
      comment-locked: true
      left-aside: true
      right-aside-top: true
      right-aside-bottom: true
      bottom-cta: true
      pin-it: true
      download: false
      download-file:
  -
    scope:
      path: "_posts/book"
    values:
      layout: chapter
      end: false
      is-post: true
      comments: true
      comment-locked: false
      left-aside: true
      right-aside-top: true
      right-aside-bottom: true
      bottom-cta: true
      pin-it: true
      download: false
      download-file:

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

############################################################
# Site configuration for the Auto-Pages feature
autopages:
  enabled: true

  collections:
    layouts:
      - 'autopage.html'
    title: 'US Money :coll' # :coll is replaced by the collection name
    permalink: '/book/:coll'

  categories:
    layouts:
      - 'autopage.html'
    title: ':cat Posts'
    permalink: '/category/:cat'

  tags:
    layouts:
      - 'autopage.html'
    title: 'Posts in category :tag'
    permalink: '/category/:tag'
