backend:
  name: git-gateway
  branch: master

media_folder: "src/assets/images"
public_folder: "assets/images"
media_library:
  name: uploadcare
  config:
    publickey: 7e16f30c88d308040803

display_url: https://usmoney.netlify.com

collections:
  - label: "US Money Sections"
    name: "book-sections"
    folder: "src/my_collections/_posts/book"
    sort: "section-number:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "chapter"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Subtitle 2", name: "subtitle-2", widget: "string", required: false}
      - {label: "Focus Keyword", name: "focus-keyword", widget: "string", required: false}
      - {label: "Meta Description", name: "meta-description", widget: "string", required: false}
      - {label: "Section Number", name: "section-number", widget: "number", valueType: "int", required: true}
      - {label: "Chapter Number", name: "chapter-number", widget: "number", valueType: "int", required: true}
      - {label: "Next Section Number", name: "next-section", widget: "number", valueType: "int" required: true}
      - {label: "Discourse Page", name: "discourse-page", widget: "string", required: false}
      - {label: "Publish Date/Time", name: "date", widget: "datetime", default: ""}
      - {label: "Add Social Share Links", name: "share", widget: "boolean", default: true, required: false}
      - {label: "Allow Comments", name: "comments", widget: "boolean", default: false, required: false}
      - {label: "Commenting is Locked (no new comments allowed)", name: "comments-locked", widget: "boolean", default: false, required: false}
      - {label: "Include Left Aside", name: "left-aside", widget: "boolean", default: true, required: false}
      - {label: "Include Top Right Aside", name: "right-aside-top", widget: "boolean", default: true, required: false}
      - {label: "Include Bottom Right Aside", name: "right-aside-bottom", widget: "boolean", default: true, required: false}
      - {label: "Include Bottom CTA (Section for comments, etc.)", name: "bottom-cta", widget: "boolean", default: true, required: false}
      - {label: "Include Download Link", name: "download", widget: "boolean", default: false, required: false}
      - {label: "Download File URL", name: "download-file", widget: "string", required: false}
      - {label: "Allow Pinterest Pinning on Image", name: "pin-it", widget: "boolean", default: true, required: false}
      - {label: "Featured Image", name: "image", widget: "string", required: false}
      - {label: "Featured Image Alt Text", name: "image-alt", widget: "string", required: false}
      - {label: "Share Image (resize for Facebook/Twitter Cards)", name: "share-image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: categories, widget: list, default: ["book"], required: false}
      - {label: "Tags", name: tags, widget: list, default: ["money"], required: false}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - label: "Blog Posts"
    name: "post"
    folder: "src/my_collections/_posts/blog"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date/Time", name: "date", widget: "datetime", default: ""}
      - {label: "Add Social Share Links", name: "share", widget: "boolean", default: true, required: false}
      - {label: "Allow Comments", name: "comments", widget: "boolean", default: false, required: false}
      - {label: "Commenting is Locked (no new comments allowed)", name: "comments-locked", widget: "boolean", default: false, required: false}
      - {label: "Include Left Aside", name: "left-aside", widget: "boolean", default: true, required: false}
      - {label: "Include Top Right Aside", name: "right-aside-top", widget: "boolean", default: true, required: false}
      - {label: "Include Bottom Right Aside", name: "right-aside-bottom", widget: "boolean", default: true, required: false}
      - {label: "Include Bottom CTA (Section for comments, etc.)", name: "bottom-cta", widget: "boolean", default: true, required: false}
      - {label: "Allow Pinterest Pinning on Image", name: "pin-it", widget: "boolean", default: true, required: false}
      - {label: "Include Download Link", name: "download", widget: "boolean", default: false, required: false}
      - {label: "Download File URL", name: "download-file", widget: "string", required: false}
      - {label: "Featured Image", name: "image", widget: "string", required: false}
      - {label: "Featured Image Alt Text", name: "image-alt", widget: "string", required: false}
      - {label: "Share Image (resize for Facebook/Twitter Cards)", name: "share-image", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: categories, widget: list, default: [""], required: false}
      - {label: "Tags", name: tags, widget: list, default: [""], required: false}
    meta:
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - label: "Pages"
    name: "pages"
    folder: "src/pages"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Display Title", name: "display-title", widget: "boolean", default: true, required: false}
      - {label: "Featured Image", name: "image", widget: "string", required: false}
      - {label: "Permalink ( /page-url-name/ )", name: "permalink", widget: "string", required: false}
      - {label: "Add Social Share Links", name: "share", widget: "boolean", default: false, required: false}
      - {label: "Allow Comments", name: "comments", widget: "boolean", default: false, required: false}
      - {label: "Include Left Aside", name: "left-aside", widget: "boolean", default: true, required: false}
      - {label: "Include First Right Aside", name: "right-aside-top", widget: "boolean", default: true, required: false}
      - {label: "Allow Pins", name: "pin-it", widget: "boolean", default: true, required: false}
      - {label: "Include Second Right Aside (CTA)", name: "right-aside-bottom", widget: "boolean", default: true, required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - label: "Homepage"
    name: "Home-Page"
    files:
      - label: "Home"
        name: "home"
        file: "src/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
          - {label: "Display Title", name: "display-title", widget: "boolean", default: true}
          - {label: "Homepage", name: "homepage", widget: "hidden", default: "true"}

          - {label: "Body", name: "body", widget: "markdown"}
  - label: "Comments"
    name: "Comments"
    folder: "src/my_collections/_comments"
    sort: "date:desc"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "hidden"}
      - {label: "id", name: "_id", widget: "hidden"}
      - {label: "email", name: "email", widget: "hidden"}
      - {label: "replying_to", name: "replying_to", widget: "hidden"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Approved", name: "approved", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "hidden"}
  - label: "Book Reviews"
    name: "book-reviews"
    folder: "src/my_collections/_book-reviews"
    sort: "date:desc"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "hidden"}
      - {label: "id", name: "_id", widget: "hidden"}
      - {label: "email", name: "email", widget: "hidden"}
      - {label: "replying_to", name: "replying_to", widget: "hidden"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Approved", name: "approved", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "hidden"}
  - label: "Default Content and Settings"
    name: "defaults"
    format: yml
    extension: yml
    files:
      - label: "Default Content and Settings File"
        name: "defaults-file"
        file: "./_config.yml"
        fields:
          - name: author
            label: Author
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Email, name: email, widget: string}
              - {label: Picture, name: picture, widget: string}
              - {label: URL, name: url, widget: string}
              - {label: Bio, name: bio, widget: markdown}
          - name: company
            label: Company
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Location, name: location, widget: string}
              - {label: Logo, name: logo, widget: string}
              - {label: Phone, name: phone, widget: string}
          - name: analytics
            label: Analytics
            widget: object
            fields:
              - {label: Google, name: google, widget: string}
              - {label: Hotjar, name: hotjar, widget: string}
              - {label: Momently, name: momently, widget: string}
          - name: mailchimp
            label: Mailchimp
            widget: object
            fields:
              - {label: "Subscribe Postback", name: post, widget: string}
              - {label: "Hidden Value", name: hidden, widget: string}
          - name: reCaptcha
            label: reCaptcha
            widget: object
            fields:
              - {label: "Site Key", name: siteKey, widget: string}
              - {label: Secret, name: secret, widget: string}
              - {label: "Touch Icon", name: "touch-icon", widget: "string"}
              - {label: "Fav Icon", name: "fav-icon", widget: "string"}
              - {label: "Lead Google Post Script", name: "lead-post-script", widget: "string"}
              - {label: "Cloudinary Name", name: "cloudinary-name", widget: "string"}
              - {label: "Default Right-Aside CTA", name: "default-right-aside-cta", widget: "text"}
              - {label: "Privacy Policy (Short Version)", name: "privacy-policy-comment", widget: "text"}
              - {label: "Comment Policy", name: "comment-policy", widget: "text"}
              - {label: "Comment Policy", name: "comment-policy", widget: "text"}
